version: '3'
services:
  mongodb:
    image: mongo:5.0.24
    ports:
      - "27017:27017"

  justdo:
    build: .
    image: brianatjustdo/justdo:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - mongodb 